name: Daily CKM Change Requests updated to JIRA

on:
  #schedule:
  # - cron: '0 0 * * MON-FRI'  #At 00:00 on every day-of-week from Monday through Friday. (see https://crontab.guru/ for configuration)

  workflow_dispatch:      # Allow manual trigger from GitHub UI

env:
    jira_account: ${{ secrets.SECRET_JIRA_USER_EMAIL }}
    jira_token: ${{ secrets.SECRET_JIRA_API_TOKEN }}

jobs:
  update-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run extractor script
        run: |
          python workflow_v6.py
          
      - name: Commit and push updated change requests
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CKM_Change_Requests.xlsx
          git commit -m "Automated daily change request update" || echo "No changes to commit"
          git push

